#!/usr/bin/env bash

set -e

mkdir -p "$1"

BASE="$(realpath $1)"


cd "$BASE"

mkdir -p island mainland

cd "$BASE/island"

git init

mkdir conflict
echo 1 > uptodate
git add .
git commit -m "clear"

echo 2 > dirty


