[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }


[[language]]
name = "json"
auto-format = false
formatter = { command = "jq", args = ["."] }


[[language]]
name = "xml"
auto-format = false
formatter = { command = "yq", args = ["-P", "-o", "xml"] }


[[language]]
name = "toml"
auto-format = false
formatter = { command = "yq", args = ["-P", "-o", "toml"] }

[[language]]
name = "bash"
auto-format = false
formatter = { command = "shfmt", args = [] }

