#!/usr/bin/env bash

FILEPATH="$(realpath --no-symlinks "$1")"

CONFIG_ISLAND_DIR="$HOME/files/config"
CONFIG_MAINLAND_DIR="$(realpath $HOME/.config)/"

if echo "$FILEPATH" | grep "^$CONFIG_MAINLAND_DIR" &>/dev/null; then
    CONFIG_MAINLAND_DIR="${CONFIG_MAINLAND_DIR%/}/"

    SUFFIX="${FILEPATH/$CONFIG_MAINLAND_DIR/}"

    NUT_DIR_NAME="${SUFFIX%/*}"

    NUT_DIR_PATH="$CONFIG_ISLAND_DIR/$NUT_DIR_NAME"

    NUT_DFS_PATH="$NUT_DIR_PATH/.dfs"

    dfm "$CONFIG_ISLAND_DIR/$SUFFIX" "$FILEPATH" -f "$NUT_DFS_PATH"
fi


