#!/usr/bin/env bash

RESOLUTIONS=($(wlr-randr | grep -e DP-1 -e current | awk '{printf("%s ", $1)}'))

current() {
    wlr-randr | grep -e DP -e current -e Position -e Scale | sed '/current/s/^[ ]*/  Mode: /g'
}

current

if wlr-randr | grep DP-1 | grep Q2790; then
	wlr-randr --output DP-1 --mode 2560x1440 --scale 1.0
fi

if [ "${RESOLUTIONS[0]}" = "DP-1" ]; then
    wlr-randr --output DP-1 --pos 0,0
    xstart=$(echo "${RESOLUTIONS[1]}" | awk -Fx '{print $1}')
    wlr-randr --output eDP-1 --pos $xstart,0 --scale 1.4
else
    wlr-randr --output DP-1 --pos 0,0
    xstart=$(echo "${RESOLUTIONS[2]}" | awk -Fx '{print $1}')
    wlr-randr --output eDP-1 --pos $xstart,0 --scale 1.4
fi

X=0
Y=0


echo "============================="
current

