#!/usr/bin/env bash

IDX=$(git rev-parse --show-toplevel | md5sum | awk NF=1)

if [ "$1" = '-k' ]; then
    emacsclient -s "$IDX" -e '(save-buffers-kill-emacs)'
    exit
fi

emacsclient -nw -c -s "$IDX" "$@" || {
    emacs --bg-daemon="$IDX" && emacsclient -nw -c -s "$IDX" "$@"
}
