#!/usr/bin/env bash

export HOME=$HOME/.fake_home

mkdir -p "$HOME"

case "$1" in
    f)
        firefox --no-remote &!
        ;;
    c)
	    export HTTP_PROXY=http://127.0.0.1:7890; export HTTPS_PROXY=http://127.0.0.1:7890
	    chromium --enable-features=UseOzonePlatform --ozone-platform=wayland &!
        ;;
esac
