#!/usr/bin/env bash

branch="$(git branch -a | sort | fzf | sed -e 's/^[[:space:]]*//g' -e 's/[[:space:]]*$//g' -e 's|remotes/origin/||g')"

if [ x = "x${branch}" ]; then
    echo 'empty branch name'
    exit 1
fi


git checkout "${branch}"
