#!/usr/bin/env bash

set -eu

declare -a DSTS=()
WRITE_FLAG=false
FILE_TYPE=""

ff_sh() {
    local filepath="$1"
    if $WRITE_FLAG; then
        shfmt -w -i 4 "$filepath"
    else
        shfmt -i 4 "$filepath"
    fi
}

ff_py() {
    local filepath="$1"
    if $WRITE_FLAG; then
        ruff format --no-cache "$filepath"
    else
        ruff format --preview --no-cache "$filepath"
    fi
}

ff_json() {
    local filepath="$1"
    if $WRITE_FLAG; then
        yq -P -o json -i "$filepath"
    else
        yq -P -o json "$filepath"
    fi
}

ff_yaml() {
    local filepath="$1"
    if $WRITE_FLAG; then
        yq -P -o yaml -i "$filepath"
    else
        yq -P -o yaml "$filepath"
    fi
}

ff_xml() {
    local filepath="$1"
    if $WRITE_FLAG; then
        yq -P -o xml -i "$filepath"
    else
        yq -P -o xml "$filepath"
    fi
}

ff_toml() {
    local f="$1"
    if $WRITE_FLAG; then
        topiary format "$f"
    else
        cat "$f" | topiary format --language toml
    fi
}

kfmt_path_ext() {
    local ext="${2:-}" filepath="$1"
    case "$ext" in
    sh) ff_sh "$filepath" ;;
    py) ff_py "$filepath" ;;
    json) ff_json "$filepath" ;;
    toml) ff_toml "$filepath" ;;
    xml) ff_xml "$filepath" ;;
    esac
}

format_file() {
    local f mime ext
    f="$1"
    ext="$(echo "$f" | awk -F'.' '{if ($0 != $NF) {print $NF}}')"

    if [ -n "$ext" ]; then
        kfmt_path_ext "$f" "$ext"
    else
        mime="$(file --mime "$f")"
        case "$mime" in
        *text/x-shellscript*)
            kfmt_path_ext "$1" "sh"
            ;;
        *text/x-script.python*)
            kfmt_path_ext "$1" "py"
            ;;
        esac
    fi
}

while [ $# -gt 0 ]; do
    case "$1" in
    '-w') WRITE_FLAG=true ;;
    '-t')
        shift
        FILE_TYPE="$1"
        ;;
    -*)
        echo "Unknown Option $1"
        exit 1
        ;;
    *) DSTS=("${DSTS[@]}" "$1") ;;
    esac
    shift
done

if [ "x$FILE_TYPE" != "x" ]; then
    kfmt_path_ext "${DSTS[0]}" "$FILE_TYPE"
    exit
fi

for dst in "${DSTS[@]}"; do
    format_file "$dst"
done
