#!/usr/bin/env bash

export KV_FILE="$CHIN_PRIVATE_DIR/kkv/kkv"
export NL="​⮰​"
export SEP="==="

export SHELL="/usr/bin/bash"
export IS_MSYS="$(uname -o | grep '^Msys' >/dev/null)"
export IS_WAYLAND=$(test -n "$WAYLAND_DISPLAY" && echo true || echo false)

init() {
    set -eu

    local k_dir="${KV_FILE%/kkv}"
    mkdir -p "$k_dir" && cd "$k_dir"
    git init
    touch kkv
    git add .
    git commit -m "init"
}

_edit() {
    cd "${KV_FILE%/*}"
    git add .
    git commit -m "backup"
    vim "${KV_FILE}" </dev/tty >/dev/tty
}
export -f _edit

_copy() {
    local content
    content="$(echo "$1" | grep -Eo '\{\{.*}}')"
    [ -z "$content" ] && content="$1"
    content="$(echo "$content" | sed 's/^{{//g;s/}}$//g' | sed -z "s/$NL/\n/g")"

    if $IS_MSYS; then
        echo "$content" >/dev/clipboard
    elif $IS_WAYLAND; then
        echo "$content" | wl-copy
    fi
}

AWK_SCRIPT="$(
    cat <<EOF
BEGIN { COM="" }

{
  if (\$0 == "$SEP") { print COM; COM="" }
  else if (COM == "") { COM=\$0 }
  else { COM=COM"$NL"\$0 }
}

END { print COM }

EOF
)"

FZF_ARGS=(
    --preview-window=right:wrap
    --preview="echo {} | sed -z 's/$NL/\n/g'"
    --bind="alt-e:execute(_edit)+abort"
)

if [ "$1" = "init" ]; then
    init
    exit
fi

RESULT="$(awk "$AWK_SCRIPT" "$KV_FILE" | fzf "${FZF_ARGS[@]}")"
_copy "$RESULT"

# For windows
# ##!/usr/bin/env bash
# TOOLS_DIR="/d/Tools"
# export PATH="$TOOLS_DIR/cmd:$TOOLS_DIR/msys64/usr/bin:$PATH"
# SCRIPT_DIR="$(dirname "$(realpath "$0")")"
# export CHIN_PRIVATE_DIR="${SCRIPT_DIR%/*}"
# FILES_DIR="${CHIN_PRIVATE_DIR%/*}"
# bash -c "$FILES_DIR/config/scripts/kkv"
#
# d:/tools/alacritty/alacritty.exe -e "d:/tools/msys64/usr/bin/bash -c d:/files/private/kkv/kkv-wrapper"
