#!/usr/bin/env bash

export KV_FILE="$CHIN_PRIVATE_DIR/kkv/kkv"
export NL="​⮰​"
export SEP="==="

export SHELL=bash
export IS_MSYS="$(uname -o | grep '^Msys' >/dev/null)"
export IS_WAYLAND=$(test -n "$WAYLAND_DISPLAY" && echo true || echo false)

init() {
    set -eu

    local k_dir="${KV_FILE%/kkv}"
    mkdir -p "$k_dir" && cd "$k_dir"
    git init
    touch kkv
    git add .
    git commit -m "init"
}

_edit() {
    cd "${KV_FILE%/*}"
    git add .
    git commit -m "backup"
    vim "${KV_FILE}"
}
export -f _edit

_copy() {
    local content
    content="$(echo "$1" | grep -Eo '\{\{.*}}')"
    [ -z "$content" ] && content="$1"
    content="$(echo "$content" | sed 's/^{{//g;s/}}$//g' | sed -z "s/$NL/\n/g")"

    if $IS_WAYLAND; then
        echo "$content" | wl-copy
    elif $IS_MSYS; then
        echo "$content" >/dev/clipboard
    fi
}
export -f _copy

AWK_SCRIPT="$(
    cat <<EOF
BEGIN { COM="" }

{
  if (\$0 == "$SEP") { print COM; COM="" }
  else if (COM == "") { COM=\$0 }
  else { COM=COM"$NL"\$0 }
}

END { print COM }

EOF
)"

FZF_ARGS=(
    --preview-window=right
    --preview="echo {} | sed -z 's/$NL/\n/g'"
    --bind="alt-e:execute(_edit)+abort"
    --bind="return:execute(_copy {})"
)

if [ "$1" = "init" ]; then
    init
    exit
fi

while true; do
    RESULT="$(awk "$AWK_SCRIPT" "$KV_FILE" | fzf "${FZF_ARGS[@]}")"

    sleep 0.5
done
