#!/usr/bin/env bash

podman pod start pod_postgres
podman pod start pod_mariadb
chnots --config ~/.config/chnots/config.toml &>/dev/null &!
lettura --config ~/Projects/lettura/data/config.example.toml &>/dev/null &!
code-server &> /tmp/code-server.log &!
