#!/usr/bin/env sh

image() {
    if [ -n "$PREVIEW_LINES" ]; then
        chafa "$1" -f sixel -s ${PREVIEW_COLUMNS}x${PREVIEW_LINES} --animate false
    else
        chafa "$1" -f sixel --animate false
    fi
}

highcat() {
    highlight --out-format=ansi "$@"
}

fontcat() {
    magick -size 800x600 xc:#ffffff -font "$1" -pointsize 48 -gravity center -fill '#000000' \
           -annotate +0+0 'ABCDEFHIJKLMN\nOPQRSTUVWXYZ\nabcdefhijklmn\nopqrstuvwxyz\n1234567890\n!@#$\%\^&*()_+-=\n\\[]{},./<>?:";'"'" \
           -flatten "$CACHE"
    otfinfo --info "$1"
    image "$CACHE"
}

handle_ext() {
    local ext
    ext="${1##*.}"

    CACHE="$HOME/.cache/lf/thumbnail.$(realpath "$1" | md5sum | awk '{print $1}').png"
    case "${ext,,}" in
        tgz|tar.gz)
            tar tzf "$1"
            return
            ;;
        tar.bz2|tbz2)
            tar tjf "$1"
            return
            ;;
        tar.txz|txz)
            xz --list "$1"
            return
            ;;
        tar)
            tar tf "$1"
            return
            ;;
        zip|jar|war|ear|oxt)
            unzip -l "$1"
            return
            ;;
        rar)
            unrar l "$1"
            return
            ;;
        md)
            glow "$1"
            return
            ;;
        7z)
            7z l "$1"
            return
            ;;
        [1-8])
            man "$1" | col -b
            return
            ;;
        o)
            nm "$1"
            return
            ;;
        torrent)
            transmission-show "$1"
            return
            ;;
        iso)
            iso-info --no-header -l "$1"
            return
            ;;
        odt|ods|odp|sxw)
            odt2txt "$1"
            return
            ;;
        doc)
            catdoc "$1"
            return
            ;;
        docx)
            docx2txt "$1" -
            return
            ;;
        xml|html)
            w3m -dump "$1"
            return
            ;;
        xls|xlsx)
            ssconvert --export-type=Gnumeric_stf:stf_csv "$1" "fd://1" | highcat --language=csv
            return
            ;;
        wav|mp3|flac|m4a|wma|ape|ac3|og[agx]|spx|opus|as[fx]|mka)
            exiftool "$1"
            return
            ;;
        pdf)
            if [ ! -f "${CACHE}.jpg" ]; then
                pdftoppm -jpeg -f 1 -singlefile "$1" "${CACHE}"
            fi
            image "${CACHE}.jpg"
            return
            ;;
        epub)
            [ ! -f "$CACHE" ] && \
                epub-thumbnailer "$1" "$CACHE" 1024
            image "$CACHE"
            return
            ;;
        cbz|cbr|cbt)
            [ ! -f "$CACHE" ] && \
                comicthumb "$1" "$CACHE" 1024
            image "$CACHE"
            return
            ;;
        avi|mp4|wmv|dat|3gp|ogv|mkv|mpg|mpeg|vob|fl[icv]|m2v|mov|webm|ts|mts|m4v|r[am]|qt|divx)
            [ ! -f "${CACHE}.jpg" ] && \
                ffmpegthumbnailer -i "$1" -o "${CACHE}.jpg" -s 0 -q 5
            image "${CACHE}.jpg"
            return
            ;;
        bmp|jpg|jpeg|png|xpm|webp|tiff|gif|jfif|ico)
            image "$1"
            return
            ;;
        svg)
            [ ! -f "${CACHE}.jpg" ] && \
                convert "$1" "${CACHE}.jpg"
            image "${CACHE}.jpg"
            return
            ;;
        ino)
            highcat --language=cpp "$1"
            return
            ;;
        ttf|otf)
            fontcat "$1"
            return
            ;;
        *)
            highcat "$1"
            return
            ;;
    esac
}

if [ -d "${1}" ]; then
    ls -lh "${1}"
else
    handle_ext "$1"
fi
exit 0
