#!/usr/bin/env bash
#
#

set -e

export PASSWORD_STORE_DIR="/home/chin/.private/box0/password-store"
export SDL_VIDEODRIVER=wayland
export GTK_THEME=adw-gtk3
export MOZ_ENABLE_WAYLAND=1

export GRADLE_USER_HOME=$HOME/Supply/gradle
export ANDROID_SDK_ROOT=$HOME/Supply/Android/Sdk
export GTK_USE_PORTAL=0

#export LIBVA_DRIVER_NAME=nvidia
#export XDG_SESSION_TYPE=wayland
#export GBM_BACKEND=nvidia-drm
#export __GLX_VENDOR_LIBRARY_NAME=nvidia
#export NVD_BACKEND=direct
#export ELECTRON_OZONE_PLATFORM_HINT=auto


#Hyprland
niri > ~/niri.log
