" About syntax
syntax on

" About indent
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent

filetype plugin indent on
filetype indent on

" Delete by backspace
" :help 'backspace'
set backspace=2

" Emacs like indent key
function IndentLine()
  let ofpos = match(getline(line(".")),'\S')
  if ofpos == -1
   call setline(line("."), "_")
   execute "normal! ==Di  "
   return
  endif

  let diff = col(".") - ofpos
  let diff = diff < 1 ? 0 : (diff - 1)

  if diff == 0
    let command = "normal! =="
  else
    let command = "normal! ==" . diff . "l"
  endif
  execute command
endfunction

inoremap <tab> <C-O>:call IndentLine()<CR>
nnoremap <tab> :call IndentLine()<CR>
vmap <tab> ==

set laststatus=2
set statusline=%m%r%w\ %F\ \ %y\ %=\ \ %l/%L,\ %c\ %{&ff}
